### PR TITLE
Update range_set.rb

### PR DESCRIPTION
**Pull request by weaksauce**
Removing the modules will allow the static lib to work. not sure how you would calls the function nested inside a few modules from inside objective-c. There might be a way but RM is not that well documented really.

### CODE REVIEW

**Comment by camertron** [comment]
Awesome @weaksauce thanks for the help! Seems to be working now. Still running into odd bugs here and there, but making progress. For example, if I have a ruby method like this:

``` ruby
def always_false
  false
end
```

Objective-C thinks this method returns `YES`. In fact, I haven't yet been able to get a false value from Ruby to Obj-C. Not once. I even tried this:

``` ruby
def always_false
  1 == 2
end
```

and I still got `YES` in Obj-C. Weird.

**Comment by camertron** [comment]
In case anyone else stumbles on this thread, here's how I got boolean return values from Ruby working in Objective-C:

``` ruby
# ruby code
class MyClass
  def always_false
    false
  end
end
```

``` objective-c
// objective-c code
@interface MyClass : NSObject {
  - (BOOL) alwaysFalse;
  - (BOOL) always_false;
@end

@implementation MyClass {
  - (BOOL) alwaysFalse {
    NSNumber* retval = [self always_false];
    return [retval isEqual: @(YES)];
  }
@end
```

**Comment by weaksauce** [comment]
fwiw. I just did a test on the repo that you supplied and just added a class method on RangeSet with the following:

``` ruby
    class RangeSet
      class << self
        def always_false
          false
        end
end
end
```

and the calling code

``` obj-c
@interface RangeSet : NSObject
+ (RangeSet*) from_array: (NSArray*)array;
+ (BOOL) always_false;
@end
```

and the result was NO when inspecting it so there is something else going on in your code or the interpreter.

**Comment by weaksauce** [comment]
I played around with it a bit more and it looks like RM is returning the values as nsnumbers so if you want to use it you will need to convert it I suppose.

**Comment by camertron** [comment]
Yeah that's what I ended up doing.

**Pull request closed without merging**
